language: csharp
solution: TestMockApplication.sln
mono: none
dotnet: 2.1

install:
- dotnet restore

script:
- dotnet build
- dotnet test TestMockApplicationUnitTests/TestMockApplicationUnitTests.csproj