language: csharp
solution: TestMockApplication.sln

matrix:
  include:
    - dotnet: 2.1
      mono: none
      #env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest
    
install:
  - nuget restore TestMockApplication.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TestMockApplication.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll