language: csharp
solution: TestMockApplication.sln
mono: none
dotnet: 2.1

notifications:
    slack: omegawave:2tDZBeJPIzYRnsNG2sD2ArH2

install:
- dotnet restore

script:
- dotnet build
- dotnet test TestMockApplicationUnitTests/TestMockApplicationUnitTests.csproj